using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Threading;

namespace ParallelRandomNumberGenerator
{
    class Program
    {
        /// <summary>
        /// Main program execution starts here
        /// </summary>
        /// <param name="args"></param>
        static void Main(string[] args)
        {
            // Fetch User Inputs for 
            //N - Number of Threads
            int numberOfThreads;

            //M - Maximum Random Number Generated
            int maxNumberOfValuesGenerated;

            //X - Lowest Number Generated by Random
            int lowestNumberGenerated;

            //Y - Highest Number Generated by Random
            int highestNumberGenerated;

            Console.WriteLine("Enter the number of threads:");
            int.TryParse(Console.ReadLine(), out numberOfThreads);

            Console.WriteLine("Enter maximum number of Random generated:");
            int.TryParse(Console.ReadLine(), out maxNumberOfValuesGenerated);

            Console.WriteLine("Enter Lowest possible number:");
            int.TryParse(Console.ReadLine(), out lowestNumberGenerated);

            Console.WriteLine("Enter maximum possible number:");
            int.TryParse(Console.ReadLine(), out highestNumberGenerated);


            Parallel.For(1, maxNumberOfValuesGenerated, new ParallelOptions() { MaxDegreeOfParallelism = numberOfThreads }, value => 
            {
                // generate a number
                int number = ThreadSafeRandomGenerator.GenerateWithInBounds(lowestNumberGenerated, highestNumberGenerated);
                int threadId = System.Threading.Thread.CurrentThread.ManagedThreadId;
                    
                // dispatch on UI thread to display
                PrintValues(number, threadId);
            });

            Console.ReadKey();
        }

        /// <summary>
        /// Prints the result and threadId
        /// </summary>
        /// <param name="result"></param>
        /// <param name="threadId"></param>
        static public void PrintValues(int result, int threadId)
        {
            Console.WriteLine("The value generated: {0} , on ThreadId: {1} ", result, threadId);
        }
    }
}
